language: node_js
node_js:
  - "6.8"
  - "7"
services:
  - docker
env:
  - "AUTH=true USER=user PASSWORD=pw"
  - "AUTH=false"
install: npm install
before_script:
  - docker build -t ase .
  - docker run -d -p 4000:4000 -e AUTH=$AUTH -e USER=$USER -e PASSWORD=$PASSWORD ase
script:
  - npm run lint
  - npm test
notifications:
  email:
    - dennis.wolters@upb.de
