language: node_js
node_js:
  - "6.8"
  - "7"
env:
  - "AUTH=true USER=user PASSWORD=pw"
  - "AUTH=false"
install: npm install
before_script: npm start
script:
  - npm run lint
  - npm test
notifications:
  email:
    - dennis.wolters@upb.de
